channels:
- conda-forge
dependencies:
- python=3.9.16
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - google-cloud-storage==2.7.0
  - ipython==8.12.0
  - pydantic==1.10.5
  - timm==0.9.16
  - torch==1.13.1
  - wandb==0.13.10
name: mlflow-env
